url: "https://lovesini2152.github.io"
baseurl: "/ar-interaction-patterns"

collections:
  patterns:
    output: true
    permalink: /patterns/:name/
  technology:       # ← 修正缩进：必须与 patterns 对齐
    output: true
    permalink: /technology/:name/

include:
  - _patterns
  - _technology     # ← 你也需要将 _technology 文件夹包含进构建中

defaults:
  - scope:
      path: ""
      type: patterns
    values:
      layout: pattern
  - scope:
      path: ""
      type: technology
    values:
      layout: tech  # 或你将来可以为每个技术项创建专属 layout，如 layout: tech
