url: "https://lovesini2152.github.io"
baseurl: "/ar-interaction-patterns"

collections:
  patterns:
    output: true
    permalink: /patterns/:name/

  technology:
    output: true
    permalink: /technology/:name/

  studies:
    output: true
    permalink: /studies/:name/

include:
  - _patterns
  - _technology
  - _studies

defaults:
  - scope:
      path: ""
      type: patterns
    values:
      layout: pattern

  - scope:
      path: ""
      type: technology
    values:
      layout: tech

  - scope:
      path: ""
      type: studies
    values:
      layout: study
