url: "https://lovesini2152.github.io"
baseurl: "/ar-interaction-patterns"

collections:
  patterns:
    output: true
    permalink: /patterns/:name/

include:
  - _patterns

defaults:
  - scope:
      path: ""
      type: patterns
    values:
      layout: pattern
